### ISSUE TITLE
TypeError: No graphs defined

### ISSUE THREAD

**Issue by ooker777** [jsongraph/jgf-dot#8]
I run the command and get this error:

```
PS D:\Quả Cầu\B Nội dung\Knowledge graphs\Cây vấn đề\.obsidian\plugins\juggl\issue tree> jgfdot .\graph.json > graph.dot
C:\Users\ganuo\AppData\Roaming\npm\node_modules\jgf-dot\node_modules\graphlib-json-graph\index.js:19

        throw new TypeError("No graphs defined");
        ^

TypeError: No graphs defined
    at toGraph (C:\Users\ganuo\AppData\Roaming\npm\node_modules\jgf-dot\node_modules\graphlib-json-graph\index.js:19:8)
    at toDot (C:\Users\ganuo\AppData\Roaming\npm\node_modules\jgf-dot\index.js:7:22)
    at C:\Users\ganuo\AppData\Roaming\npm\node_modules\jgf-dot\bin\cli.js:9:24
    at Gatherer.<anonymous> (C:\Users\ganuo\AppData\Roaming\npm\node_modules\jgf-dot\node_modules\gather-stream\index.js:41:5)
    at Gatherer.emit (events.js:412:35)
    at finish (internal/streams/writable.js:657:10)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

Here is the JSON: https://pastebin.com/Fy2tTEg2

This is the snippet from line 17 to line 21 in [the index.js](https://github.com/jsongraph/jgf-dot/blob/master/index.js "jgf-dot/index.js at master · jsongraph/jgf-dot")
```js
	graphlibGraph.edges().forEach(function (name) {
		var edge = graphlibGraph.edge(name);
		if (edge.metadata)
			edge.metadata = JSON.stringify(edge.metadata);
	});
```

I use Windows 11 Home

**Comment by wilhelmy** [comment]
I have the same issue with a smaller JSON file (also complaining about line 19 in index.js without any additional information):

```json
{
  "type": "graph",
  "label": "Network topology as seen from 192.168.1.5",
  "nodes": [
    {
      "label": "fe80::346a:32ff:fed4:be3a"
    },
    {
      "label": "fe80::5404:58ff:fed2:41b2"
    },
    {
      "label": "192.168.1.5"
    },
    {
      "label": "fe80::6055:f4ff:fe3c:c3fc"
    }
  ],
  "edges": [
    {
      "source": "fe80::346a:32ff:fed4:be3a",
      "relation": "connected",
      "target": "192.168.1.5"
    },
    {
      "source": "fe80::346a:32ff:fed4:be3a",
      "relation": "connected",
      "target": "fe80::5404:58ff:fed2:41b2"
    },
    {
      "source": "fe80::5404:58ff:fed2:41b2",
      "relation": "connected",
      "target": "fe80::6055:f4ff:fe3c:c3fc"
    }
  ]
}
```

**Comment by wilhelmy** [comment]
Seems like we're both emitting JGF v2 JSON when the library only accepts v1.
